# Generated by Django 2.0 on 2018-01-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180123_2029'),
        ('medium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
        migrations.AlterModelOptions(
            name='videolist',
            options={'verbose_name': '视频列表', 'verbose_name_plural': '视频列表'},
        ),
        migrations.AddField(
            model_name='video',
            name='thumb_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='videolist',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='user.User'),
        ),
        migrations.AlterField(
            model_name='video',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
        migrations.AlterModelTable(
            name='videolist',
            table='video_list',
        ),
    ]
