# Generated by Django 2.0 on 2018-01-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0003_auto_20180123_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_color', models.CharField(blank=True, max_length=20, null=True)),
                ('title_font_size', models.CharField(blank=True, max_length=20, null=True)),
                ('subtitle_font_size', models.CharField(blank=True, max_length=20, null=True)),
                ('title_color', models.CharField(blank=True, max_length=20, null=True)),
                ('subtitle_color', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '卡片样式',
                'verbose_name_plural': '卡片样式',
                'db_table': 'card_style',
            },
        ),
    ]
