# Generated by Django 2.0 on 2018-01-25 02:34

import apps.medium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0004_cardstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.medium.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='videolist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/video/videoList/%Y/%m/%d'),
        ),
    ]
