# Generated by Django 2.0 on 2018-01-25 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0005_auto_20180125_1034'),
    ]

    operations = [
    ]
