# Generated by Django 2.0 on 2018-01-25 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0006_auto_20180125_1117'),
    ]

    operations = [
    ]
