# Generated by Django 2.0 on 2018-01-25 03:21

from django.db import migrations, models
import util.model_tools.common


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0007_auto_20180125_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=30)),
                ('describe', models.TextField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=util.model_tools.common.img_upload_path_handler)),
            ],
            options={
                'verbose_name': '通用卡片',
                'verbose_name_plural': '通用卡片',
                'db_table': 'common_card',
            },
        ),
        migrations.AlterField(
            model_name='videolist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=util.model_tools.common.img_upload_path_handler),
        ),
    ]
