# Generated by Django 2.0 on 2018-01-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0008_auto_20180125_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncard',
            name='using',
            field=models.IntegerField(choices=[(0, '未使用'), (1, '首页')], default=0, unique=True),
        ),
    ]
