# Generated by Django 2.0 on 2018-01-25 10:45

from django.db import migrations, models
import util.model_tools.common


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0009_commoncard_using'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('describe', models.CharField(blank=True, max_length=500, null=True)),
                ('using', models.IntegerField(choices=[(0, '未使用'), (1, '首页')], default=0, unique=True)),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('imageLink', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=util.model_tools.common.img_upload_path_handler)),
                ('describe', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(1, '文件'), (2, '链接')], default=1)),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'image',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ManyToManyField(to='medium.Image'),
        ),
    ]
