# Generated by Django 2.0 on 2018-01-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0010_auto_20180125_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='images',
        ),
    ]
