# Generated by Django 2.0 on 2018-01-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('parentName', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('state', models.IntegerField(choices=[(1, '待完成'), (2, '已完成'), (3, '待改期'), (4, '已改期')], default=1)),
                ('remark', models.TextField()),
                ('course', models.ForeignKey(on_delete='SET_NULL', to='course.Course')),
            ],
        ),
    ]
