# Generated by Django 2.0 on 2018-01-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_enroll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enroll',
            options={'verbose_name': '申请表', 'verbose_name_plural': '申请表'},
        ),
        migrations.AlterModelTable(
            name='enroll',
            table='enroll_sheet',
        ),
    ]
