# Generated by Django 2.0 on 2018-01-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180117_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1),
        ),
    ]
