# Generated by Django 2.0 on 2018-01-23 08:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180117_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail_page',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='课程详情页'),
        ),
    ]
