# Generated by Django 2.0 on 2018-01-25 03:21

from django.db import migrations, models
import util.model_tools.common


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_detail_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=util.model_tools.common.img_upload_path_handler),
        ),
    ]
