# Generated by Django 2.0 on 2018-01-25 03:21

from django.db import migrations, models
import util.model_tools.common


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180123_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=util.model_tools.common.img_upload_path_handler),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=util.model_tools.common.img_upload_path_handler),
        ),
    ]
