# Generated by Django 2.0 on 2018-01-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180118_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
